
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CommitWithSignatureParameters {
    /**
    * Label: Repository path, type: entry
    */
    String repoPath
    /**
    * Label: Branch name, type: entry
    */
    String branch
    /**
    * Label: Files to add, type: textarea
    */
    String files
    /**
    * Label: Push?, type: checkbox
    */
    boolean push
    /**
    * Label: Remote name, type: entry
    */
    String remote
    /**
    * Label: Commit message, type: entry
    */
    String commitMessage

    static CommitWithSignatureParameters initParameters(StepParameters sp) {
        CommitWithSignatureParameters parameters = new CommitWithSignatureParameters()

        def repoPath = sp.getRequiredParameter('repoPath').value
        parameters.repoPath = repoPath

        def branch = sp.getRequiredParameter('branch').value
        parameters.branch = branch

        def files = sp.getRequiredParameter('files').value
        parameters.files = files

        def push = sp.getParameter('push').value == "true"
        parameters.push = push

        def remote = sp.getParameter('remote').value
        parameters.remote = remote

        def commitMessage = sp.getParameter('commitMessage').value
        parameters.commitMessage = commitMessage

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 02efd8245f36ac69c4cb7c8da8e561f5 ===
